#!/usr/bin/env bash

me=$(basename "$0")
cmd=$1
arg1=$2
arg2=$3

readonly MODE="safe"

usage() {
	printf "\n"
  printf "%-25s %s\n" "$me <session>" "attach or create"
  printf "%-25s %s\n" "$me rm <session>" "remove session"
  printf "%-25s %s\n" "$me mv <old> <new>" "rename session"
  printf "%-25s %s\n" "$me ls" "list sessions"
  printf "%-25s %s\n" "$me nuke" "remove all sessions"
	printf "\n"
  exit 1
}

tmux_find_session() {
	local name="$1"
	tmux has-session -t "$name" 2>/dev/null
}

has_argument() { [[ -n "$1" ]]; }

if ! has_argument $cmd; then
	usage
fi

case $cmd in 
	ls)
	if ! tmux list-sessions >/dev/null 2>&1; then
		echo "No tmux sessions currently exist"
		exit 1
	fi

	tmux list-sessions
	exit 0
	;;

	rm)
	if ! tmux_find_session "$arg1"; then
		echo "tmux session: $arg1 does not exist"
		exit 1
	fi

	if ! tmux kill-session -t "$arg1"; then 
		echo "Failed to terminate tmux session $arg1"
		exit 1
	fi 

	echo "tmux session $arg1 terminated successfully"
	exit 0
	;; 

	mv) 
	if ! tmux_find_session "$arg1"; then
		echo "tmux session: $arg1 does not exist"
		exit 1
	fi

	if ! has_argument "$arg2"; then
		echo "Usage: $me mv <name> <new_name>"
		exit 1
	fi

	if ! tmux rename-session -t "$arg1" "$arg2"; then
		echo "Failed to rename tmux session $arg1 to $arg2"
		exit 1
	fi 

	echo "tmux session $arg1 sucessfully renamed to  $arg2..."
	exit 0
	;;

	nuke)
	if [[ "$MODE" == "safe" ]]; then
		read -p "This will remove all tmux sessions... Are you sure(y/n)? "
		echo 
		if [[ ! $REPLY =~ ^[Yy]$ ]]; then
			[[ "$0" = "$BASH_SOURCE" ]] && echo "Nuke aborted..." && exit 1 || return 1 
		fi
	fi

	echo "Terminating all tmux sessions..."
	tmux kill-session -a
	exit 0
	;;

	*)
	session="$cmd"
	if tmux_find_session "$session"; then
		echo "Attaching to existing tmux session $session..."
		tmux attach-session -t "$session"
	else 
		echo "Creating new tmux session $session..."
		tmux new-session -s "$session"
	fi

	exit 0
	;;
esac
